### ISSUE TITLE
Fit for production use?

### ISSUE THREAD

**Issue by sivabudh** [David-Desmaisons/EasyActor#1]
Hi,

I'm about to try our EasyActor in one of my applications, but just noticed from Nuget that it hasn't been updated since 2016. I see recent commits made this past year, which is a good sign. But just want to check if I should use the library in a production app?

Thanks

**Comment by David-Desmaisons** [comment]
Hello @sivabudh , EasyActor's scope is very limited: it is a factory of actor.
As such, this is a library easily testable and optimisable. The curent version has a very high coverage and many integrated tests in order to ensure safe threathness.

There is no known bugs, and I will correct any reproducable issues.

Regarding the upcoming version, there are basically 3 changes:
 - Compatibility with .NET Standard
 - Faster implementation
 - Breaking change: simplification of LifeCycle,: the actor factory is in charge of life cycle not the cator themselves anymore.

I hope this answer your question.

**Comment by sivabudh** [comment]
Thanks for your response.
